### ISSUE TITLE
场外发言过滤问题：如果为场外发言的类型为@和回复，将不会被识别

### ISSUE THREAD

**Issue by kagangtuya-star** [sealdice/story-painter#1]
一种场外发言的类型是这样的，如果是@或者回复上一句时用场外发言的形式，就会多出一个空格，导致无法匹配到

`
布雷克(122798023) 2023/03/15 21:18:36
（可以使用现实知识（不是

**艾瑞利安(909487930) 2023/03/15 21:18:48
[CQ:reply,id=-873863910][CQ:at,qq=122798023] （这个我知道）**

布雷克(122798023) 2023/03/15 21:19:00
“布雷克觉得我们怎么伪装也没用吧。”

艾瑞利安(909487930) 2023/03/15 21:19:05
（就怕还有其他魔幻一点的原因）
`

v2染色器的结果为
`
21:18:31<玖玖>:但想了想，感觉自己应该怎么装都不会像吧

21:18:48<艾瑞利安>:（这个我知道）

21:19:00<布雷克>:“布雷克觉得我们怎么伪装也没用吧。”
`

**Comment by fy0** [comment]
解决于2.0.7版本：
![image](https://user-images.githubusercontent.com/1579850/227582465-926bc2ce-38ce-4823-a0c2-ced5cfafd5c1.png)
![image](https://user-images.githubusercontent.com/1579850/227582491-5450a51d-4718-4d6b-8204-7a9ca0def172.png)
