### ISSUE TITLE
[BUG]删除角色操作，点击取消后，对应的角色名字会被清空

### ISSUE THREAD

**Issue by kagangtuya-star** [sealdice/story-painter#15]
![9504816961ec64516061a2a5bbd88849](https://github.com/sealdice/story-painter/assets/73411104/ac564874-7716-4bfd-8791-a51dd544f13c)
![de85d133bfc05ac846b5d17d6839213d](https://github.com/sealdice/story-painter/assets/73411104/6fdaa2d5-4d99-4695-aaec-1197d3e4e21d)

对应的位置会被清空，而无法操作，必须给它重命名两次才可以进行譬如批量改名等操作。

**Comment by fy0** [comment]
#16 已修复
