### ISSUE TITLE
[BUG]染色器更新2.1版本后旧log无法在染色器识别、新log导出全是门前两棵树（log丢失）

### ISSUE THREAD

**Issue by SunnyJoyce** [sealdice/story-painter#8]
群友收集了log错误紧急收集表。在不同浏览器、不同创建时间log、不同log文本长短均复现此问题。
旧log导出链接会显示：加载日志失败，可能是序号或密码不正确。
新log导出链接会显示：展示门墙两棵树的初始log，丢失原有log，且初始log仍不能识别，显示染色失败，内容为空或无法识别此格式。

**Comment by Feather099** [comment]
补充：此为在线文档收集到的一些数据
【腾讯文档】log打开错误紧急收集！
https://docs.qq.com/sheet/DWVJYb1NvaUFuclp1

**Comment by Feather099** [comment]
二次补充：
- 在新log显示初始log的情况下，勾选编辑器染色可以顺利染色角色但不能染色对话。无论勾选与否点击调试:Flush都会导致所有初始log文本消失。
- 关于key：当key满足 [一段文本]#[另一段文本] 时，即key在非两端位置存在 # 时。无论这个key是否存在，都会复现“不能识别的初始log”这个问题。当key不满足上述规律，或没有key时，显示的初始log一切正常，可以着色也可以正常调试导出。

**Comment by fy0** [comment]
无法获取log的原因并非更新，而是https证书过期，恰好在同一天

**Comment by fy0** [comment]
> 二次补充：
> 
> * 在新log显示初始log的情况下，勾选编辑器染色可以顺利染色角色但不能染色对话。无论勾选与否点击调试:Flush都会导致所有初始log文本消失。
> * 关于key：当key满足 [一段文本]#[另一段文本] 时，即key在非两端位置存在 # 时。无论这个key是否存在，都会复现“不能识别的初始log”这个问题。当key不满足上述规律，或没有key时，显示的初始log一切正常，可以着色也可以正常调试导出。

不很明白，来一些例子和截图
感觉和2.0.6没有什么区别？
