### ISSUE TITLE
[require]在qq文字气泡框内换行后，在染色器中会出现空格

### ISSUE THREAD

**Issue by SunnyJoyce** [sealdice/story-painter#9]
当QQ文本框这样显示时：

> 叶 12:39:20
> 萨曼塔点点头，虽然仍然警戒着，但也表现出了赞同。水乐灵犹豫了片刻，看向了莉斯贝茨。她没有看她，仍然抓着头发，心乱如麻地低着头。她已经放开了勒住布莱安娜的手，布莱安娜后退了几步，转头看向她。刀无力地虚虚握着，她没有敢看向水乐灵，也没看向布莱安娜或者阿德莱多：“对不起… 灵视者，结社？我需要点时间… 我，刚刚差点杀了人…？”
> 
> 眼泪顺着脸颊留下，滴到草地上，湿润了泥土。她沉默了片刻，匆匆抬头，眨开泪花：“啊，对了，马蒂亚斯！安妮！她们还好吗？我得去把她们带回去！”
> 
> 你引领浪潮的启明 00:04:54
> “她们都很好，只是需要休息，你也是。”见莉斯贝茨放开手，阿德莱多心中略微松了口气，“慢慢来，慢慢来……我们先把她们送回去。结社的事情，等你考虑好了再答复。水乐灵，你可以一起帮忙吗？”
> “…还有，”阿德莱多对着身旁的古斯塔夫叹了口气，“萨曼塔，我可以把他交给你吗？我们还有很多事情没有了解…等回去休整过后，还需要对整件事做次总结。”

在海豹的染色器中，换行的那一行开头会出现一长段空格。
![YVBRIH 5P({%ILV@JLG1(JF](https://user-images.githubusercontent.com/128024558/227703888-427238cf-94c7-45ba-8214-66d1f9c31a25.png)

【需求】希望没有前面的空格，或者只在这段的开头有空格而不是一整段都向后空了

**Comment by fy0** [comment]
呃啊 首行缩进！

**Comment by fy0** [comment]
改了，这两种：
![image](https://user-images.githubusercontent.com/1579850/227712933-8bf592a5-284b-4bfe-9929-79919223ea37.png)

![image](https://user-images.githubusercontent.com/1579850/227712947-bc41ed17-503b-4627-b84b-fca7fca88ea9.png)
